# Generated by Django 3.2.16 on 2024-08-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_genres_title_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='yaer',
            field=models.SmallIntegerField(default=0, verbose_name='Год выпуска'),
            preserve_default=False,
        ),
    ]
