# Generated by Django 3.2.16 on 2024-08-28 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_title_yaer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='yaer',
            new_name='year',
        ),
    ]
