# Generated by Django 3.2.16 on 2024-08-28 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_rename_yaer_title_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='slug',
        ),
    ]
